Algoritmo "semnome"

Var

   x, soma : inteiro

Inicio

      escreva ("digite um valor: ")
      leia (x)
      
      enquanto x <> 0 faca
      
         se x % 2 <> 0 entao

         x <- x + 1

         fimse
      
      soma <- 5 * x + 20
      escreva ("SOMA = ", soma)
      escreval
      
      escreva ("digite outro valor: ")
      leia (x)
      
      fimenquanto

Fimalgoritmo