Algoritmo "testepara"

Var

   x, icontador, quantidade, soma : inteiro

Inicio

      escreva ("quantos numeros o cliente deseja? ")
      leia (quantidade)
      
      soma <- 0
      
      para icontador de 1 ate quantidade faca
      
      escreva ("digite um valor: ")
      leia (x)
      
      soma <- soma + x
      
      fimpara
      
      escreva ("soma = ", soma)

Fimalgoritmo